import type { Metadata } from "next";
import Link from "next/link";
import { ContinueRoute, GuideShell, PageHero } from "../site-components";

export const metadata: Metadata = { title: "Upgrade Route", description: "A practical early upgrade priority for Animal Restaurant (Anomaly) based on the actions repeated every shift.", alternates: { canonical: "/upgrades" } };

export default function Upgrades() {
  return <GuideShell><PageHero step="03 / 04" eyebrow="Progression plan" title="Upgrade route" intro="Spend to shorten the restaurant loop you repeat on every customer. Add safety only when it solves a problem you actually have." /><section className="article-section"><div className="shell article-grid"><aside className="article-toc"><strong>PRIORITIES</strong><a href="#first">Buy first</a><a href="#second">Buy second</a><a href="#later">Buy later</a><a href="#rule">Decision rule</a></aside><article className="article-body"><section id="first"><h2>1. Restaurant efficiency</h2><p>The upgrade car currently presents three choices each day. Start by looking for the repeated restaurant step that slowed the last shift; if coffee recovery already keeps pace, cooking and order improvements are usually the stronger early choice.</p><ul><li>Prefer improvements that reduce cooking or handling time.</li><li>Choose capacity only when a full station regularly blocks progress.</li><li>Do not spend just because an upgrade is available; solve the slowest repeated step.</li></ul></section><section id="second"><h2>2. Queue control</h2><p>After the drive-thru opens, two queues compete for attention. Improvements that preserve room to respond are more useful once you can already complete the basic food loop reliably.</p></section><section id="later"><h2>3. Recovery capacity</h2><p>Coffee restores sanity. Move recovery-focused upgrades higher only when your shifts consistently fail because coffee cannot keep pace; otherwise, keep strengthening the service loop you use on nearly every safe customer.</p><div className="article-note"><strong>Version-safe advice</strong>Upgrade names, prices, and balance can change. This guide ranks functions, not unverified numbers.</div></section><section id="rule"><h2>The one-question rule</h2><p>Before every purchase, ask: “Will this improve a step I use on most customers, or fix the exact reason my last shift failed?” If the answer is neither, keep the money.</p><Link href="/beginner-guide">Review the loop each upgrade should improve →</Link></section><ContinueRoute current="upgrades" /></article></div></section></GuideShell>;
}
